import 'package:flutter/material.dart';

/// Multilingual Localization Engine supporting Indian & International languages.
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const List<LanguageItem> supportedLanguages = [
    LanguageItem(code: 'en', name: 'English', nativeName: 'English'),
    LanguageItem(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'),
    LanguageItem(code: 'bn', name: 'Bengali', nativeName: 'বাংলা'),
    LanguageItem(code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'),
    LanguageItem(code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'),
    LanguageItem(code: 'mr', name: 'Marathi', nativeName: 'मराठी'),
    LanguageItem(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'),
    LanguageItem(code: 'te', name: 'Telugu', nativeName: 'తెలుగు'),
    LanguageItem(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'),
    LanguageItem(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'),
    LanguageItem(code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'Jaap',
      'tagline': 'Your practice. Your pace.',
      'taglineSub': 'A simple space to count, focus and continue your daily practice.',
      'continueBtn': 'Continue',
      'chooseLanguage': 'Choose your language',
      'whatToCount': 'What would you like to count?',
      'mantraNameHint': 'Mantra / Name (e.g. Radhe Radhe)',
      'startJaap': 'Start Jaap',
      'skipForNow': 'Skip for now',
      'navJaap': 'Jaap',
      'navHistory': 'History',
      'navMore': 'More',
      'tapToCount': 'Tap anywhere to count',
      'undo': 'Undo',
      'malaComplete': 'Mala complete',
      'mala': 'Mala',
      'malas': 'Malas',
      'jaaps': 'Jaaps',
      'of': 'of',
      'todaysPractice': "Today's Practice",
      'thisWeek': 'This Week',
      'allTime': 'All Time',
      'streak': 'days of consistent practice',
      'practice': 'Practice',
      'dailyGoal': 'Daily Goal',
      'counterStyle': 'Counter Style',
      'styleMinimal': 'Minimal Ring',
      'styleMala': 'Bead Mode',
      'soundAndHaptics': 'Sound & Haptics',
      'tapSound': 'Tap Sound',
      'completionSound': 'Completion Sound',
      'haptics': 'Haptic Feedback',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'themeSystem': 'System',
      'accent': 'Accent Color',
      'language': 'Language',
      'data': 'Data',
      'backupData': 'Export Backup (JSON)',
      'restoreData': 'Restore Backup',
      'about': 'About',
      'privacyNotice': 'Your practice stays on your device. 100% offline & private.',
      'version': 'Version 1.0.0',
      'createJaap': 'Create New Jaap',
      'editJaap': 'Edit Jaap',
      'deleteJaap': 'Delete Jaap',
      'deleteConfirm': 'Delete this Jaap and its history?',
      'cancel': 'Cancel',
      'save': 'Save',
      'add': 'Add',
      'delete': 'Delete',
      'library': 'Mantra Library',
      'meditation': 'Meditation',
      'focusMode': 'Focus Mode',
      'sankalp': 'Sankalp (Challenge)',
      'manualEntry': 'Manual Entry',
      'addPreviousJaap': 'Add Previous Jaap',
      'resetCount': 'Reset Current Count',
      'quickActions': 'Quick Actions',
      'breatheSoftly': 'Breathe softly',
      'endSession': 'End Session',
      'beginPractice': 'Begin your practice',
      'createFirstJaap': 'Create your first Jaap to start',
      'custom': 'Custom',
      'noSound': 'Off',
      'soft': 'Soft',
      'wood': 'Wood',
      'bead': 'Bead',
      'bell': 'Soft Bell',
      'templeBell': 'Temple Bell',
      'hapticOff': 'Off',
      'hapticLight': 'Light',
      'hapticMedium': 'Medium',
      'dayStreak': 'Day Streak',
      'bestStreak': 'Best Streak',
      'streakCompletedToday': 'Streak Active! You completed a mala today. Your streak is safe until 12:00 AM midnight.',
      'streakPendingToday': 'Chant at least 1 mala today before 12:00 AM midnight to maintain your streak!',
      'streakResetInfo': 'Streaks reset automatically at 12:00 AM midnight every day if no mala is completed.',
      'streakIncreased': 'Streak Increased!',
    },
    'hi': {
      'appName': 'जाप',
      'tagline': 'आपका अभ्यास। आपकी गति।',
      'taglineSub': 'गिनती करने, ध्यान केंद्रित करने और दैनिक साधना जारी रखने के लिए एक शांत स्थान।',
      'continueBtn': 'आगे बढ़ें',
      'chooseLanguage': 'अपनी भाषा चुनें',
      'whatToCount': 'आप किस नाम/मंत्र का जाप करना चाहते हैं?',
      'mantraNameHint': 'मंत्र / नाम (उदा. राधे राधे)',
      'startJaap': 'जाप शुरू करें',
      'skipForNow': 'अभी छोड़ें',
      'navJaap': 'जाप',
      'navHistory': 'इतिहास',
      'navMore': 'अन्य',
      'tapToCount': 'गिनने के लिए कहीं भी स्पर्श करें',
      'undo': 'पूर्ववत करें',
      'malaComplete': 'माला पूर्ण',
      'mala': 'माला',
      'malas': 'मालाएं',
      'jaaps': 'जाप',
      'of': 'का',
      'todaysPractice': 'आज का अभ्यास',
      'thisWeek': 'इस सप्ताह',
      'allTime': 'कुल साधना',
      'streak': 'दिनों का निरंतर अभ्यास',
      'practice': 'साधना',
      'dailyGoal': 'दैनिक लक्ष्य',
      'counterStyle': 'काउंटर शैली',
      'styleMinimal': 'न्यूनतम चक्र',
      'styleMala': 'मनका माला',
      'soundAndHaptics': 'ध्वनि व कंपन',
      'tapSound': 'स्पर्श ध्वनि',
      'completionSound': 'पूर्णता ध्वनि',
      'haptics': 'हैप्टिक कंपन',
      'appearance': 'दिखावट',
      'theme': 'थीम',
      'themeLight': 'उजाला (Light)',
      'themeDark': 'अंधेरा (Dark)',
      'themeSystem': 'सिस्टम',
      'accent': 'रंग चयन',
      'language': 'भाषा',
      'data': 'डेटा',
      'backupData': 'बैकअप निर्यात करें (JSON)',
      'restoreData': 'बैकअप पुनर्स्थापित करें',
      'about': 'जानकारी',
      'privacyNotice': 'आपकी साधना आपके डिवाइस पर सुरक्षित है। पूर्णतः ऑफलाइन।',
      'version': 'संस्करण 1.0.0',
      'createJaap': 'नया जाप जोड़ें',
      'editJaap': 'जाप बदलें',
      'deleteJaap': 'जाप हटाएं',
      'deleteConfirm': 'क्या आप इस जाप और इसके इतिहास को हटाना चाहते हैं?',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'add': 'जोड़ें',
      'delete': 'हटाएं',
      'library': 'मंत्र संग्रह',
      'meditation': 'ध्यान (Meditation)',
      'focusMode': 'एकाग्रता मोड',
      'sankalp': 'संकल्प साधना',
      'manualEntry': 'मैन्युअल प्रविष्टि',
      'addPreviousJaap': 'पिछला जाप जोड़ें',
      'resetCount': 'गिनती रीसेट करें',
      'quickActions': 'त्वरित विकल्प',
      'breatheSoftly': 'सहज श्वास लें',
      'endSession': 'सत्र समाप्त करें',
      'beginPractice': 'अपनी साधना शुरू करें',
      'createFirstJaap': 'शुरू करने के लिए अपना पहला जाप बनाएं',
      'custom': 'कस्टम',
      'noSound': 'बंद',
      'soft': 'धीमी',
      'wood': 'काष्ठ',
      'bead': 'मनका',
      'bell': 'सौम्य घंटी',
      'templeBell': 'मंदिर की घंटी',
      'hapticOff': 'बंद',
      'hapticLight': 'हल्का',
      'hapticMedium': 'मध्यम',
      'dayStreak': 'दिनों का स्ट्रीक',
      'bestStreak': 'सर्वश्रेष्ठ स्ट्रीक',
      'streakCompletedToday': 'स्ट्रीक सक्रिय है! आपने आज माला पूर्ण की है। आपकी स्ट्रीक रात 12:00 बजे तक सुरक्षित है।',
      'streakPendingToday': 'अपनी स्ट्रीक बनाए रखने के लिए आज रात 12:00 बजे से पहले कम से कम 1 माला अवश्य करें!',
      'streakResetInfo': 'यदि कोई माला पूर्ण नहीं होती है, तो स्ट्रीक प्रतिदिन रात 12:00 बजे स्वतः रीसेट हो जाती है।',
      'streakIncreased': 'स्ट्रीक बढ़ गई!',
    },
    'bn': {
      'appName': 'জপ',
      'tagline': 'আপনার সাধনা। আপনার গতি।',
      'taglineSub': 'গণনা এবং একাগ্রতার একটি শান্ত স্থান।',
      'continueBtn': 'এগিয়ে যান',
      'chooseLanguage': 'আপনার ভাষা বেছে নিন',
      'whatToCount': 'আপনি কী জপ করতে চান?',
      'mantraNameHint': 'মন্ত্র / নাম (যেমন: রাধে রাধে)',
      'startJaap': 'জপ শুরু করুন',
      'skipForNow': 'এখন এড়িয়ে যান',
      'navJaap': 'জপ',
      'navHistory': 'ইতিহাস',
      'navMore': 'আরও',
      'tapToCount': 'গণনার জন্য স্পর্শ করুন',
      'undo': 'পূর্বাবস্থায় ফেরান',
      'malaComplete': 'মালা সম্পন্ন',
      'mala': 'মালা',
      'malas': 'মালা',
      'jaaps': 'জপ',
      'of': 'এর',
      'todaysPractice': 'আজকের সাধনা',
      'thisWeek': 'এই সপ্তাহ',
      'allTime': 'সর্বকালের সাধনা',
      'streak': 'দিনের অবিচ্ছিন্ন সাধনা',
      'practice': 'সাধনা',
      'dailyGoal': 'দৈনিক লক্ষ্য',
      'counterStyle': 'কাউন্টার শৈলী',
      'styleMinimal': 'ন্যূনতম বৃত্ত',
      'styleMala': 'পুঁতির মালা',
      'soundAndHaptics': 'শব্দ ও কম্পন',
      'tapSound': 'স্পর্শ শব্দ',
      'completionSound': 'সম্পূর্ণতা শব্দ',
      'haptics': 'হ্যাপটিক প্রতিক্রিয়া',
      'appearance': 'চেহারা',
      'theme': 'থিম',
      'themeLight': 'হালকা',
      'themeDark': 'গাঢ়',
      'themeSystem': 'সিস্টেম',
      'accent': 'রং',
      'language': 'ভাষা',
      'data': 'ডেটা',
      'backupData': 'ব্যাকআপ এক্সপোর্ট',
      'restoreData': 'ব্যাকআপ রিস্টোর',
      'about': 'সম্পর্কে',
      'privacyNotice': 'আপনার সাধনা আপনার ডিভাইসে সম্পূর্ণ নিরাপদ।',
      'version': 'সংস্করণ 1.0.0',
      'createJaap': 'নতুন জপ তৈরি করুন',
      'editJaap': 'জপ সম্পাদনা',
      'deleteJaap': 'জপ মুছুন',
      'deleteConfirm': 'এই জপ এবং ইতিহাস মুছবেন?',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
      'add': 'যোগ',
      'delete': 'মুছুন',
      'library': 'মন্ত্র ভাণ্ডার',
      'meditation': 'ধ্যান',
      'focusMode': 'মনোযোগ মোড',
      'sankalp': 'সংকল্প',
      'manualEntry': 'ম্যানুয়াল এন্ট্রি',
      'addPreviousJaap': 'পূর্ববর্তী জপ যোগ করুন',
      'resetCount': 'গণনা রিসেট করুন',
      'quickActions': 'দ্রুত ক্রিয়া',
      'breatheSoftly': 'ধীরে শ্বাস নিন',
      'endSession': 'অধিবেশন শেষ',
      'beginPractice': 'সাধনা শুরু করুন',
      'createFirstJaap': 'প্রথম জপ তৈরি করুন',
      'custom': 'কাস্টম',
      'noSound': 'বন্ধ',
      'soft': 'মৃদু',
      'wood': 'কাঠ',
      'bead': 'পুঁতি',
      'bell': 'ঘণ্টা',
      'templeBell': 'মন্দির ঘণ্টা',
      'hapticOff': 'বন্ধ',
      'hapticLight': 'হালকা',
      'hapticMedium': 'মাঝারি',
      'dayStreak': 'দিনের স্ট্রিক',
      'bestStreak': 'সেরা স্ট্রিক',
      'streakCompletedToday': 'স্ট্রিক সক্রিয়! আপনি আজ মালা সম্পন্ন করেছেন। রাত ১২টা পর্যন্ত আপনার স্ট্রিক নিরাপদ।',
      'streakPendingToday': 'আপনার স্ট্রিক বজায় রাখতে আজ রাত ১২টার আগে কমপক্ষে ১টি মালা জপ করুন!',
      'streakResetInfo': 'কোনো মালা সম্পন্ন না হলে প্রতিদিন রাত ১২টায় স্ট্রিক স্বয়ংক্রিয়ভাবে রিসেট হয়ে যায়।',
      'streakIncreased': 'স্ট্রিক বৃদ্ধি পেয়েছে!',
    },
    'pa': {
      'appName': 'ਜਾਪ',
      'tagline': 'ਤੁਹਾਡਾ ਅਭਿਆਸ। ਤੁਹਾਡੀ ਗਤੀ।',
      'taglineSub': 'ਨਾਮ ਸਿਮਰਨ ਅਤੇ ਇਕਾਗਰਤਾ ਲਈ ਇੱਕ ਸ਼ਾਂਤ ਥਾਂ।',
      'continueBtn': 'ਅੱਗੇ ਵਧੋ',
      'chooseLanguage': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
      'whatToCount': 'ਤੁਸੀਂ ਕਿਸ ਨਾਮ ਦਾ ਜਾਪ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'mantraNameHint': 'ਨਾਮ / ਮੰਤਰ (ਜਿਵੇਂ ਵਾਹਿਗੁਰੂ)',
      'startJaap': 'ਜਾਪ ਸ਼ੁਰੂ ਕਰੋ',
      'skipForNow': 'ਹੁਣ ਛੱਡੋ',
      'navJaap': 'ਜਾਪ',
      'navHistory': 'ਇਤਿਹਾਸ',
      'navMore': 'ਹੋਰ',
      'tapToCount': 'ਗਿਣਨ ਲਈ ਛੋਹਵੋ',
      'undo': 'ਵਾਪਸ',
      'malaComplete': 'ਮਾਲਾ ਪੂਰੀ ਹੋਈ',
      'mala': 'ਮਾਲਾ',
      'malas': 'ਮਾਲਾਵਾਂ',
      'jaaps': 'ਜਾਪ',
      'of': 'ਵਿੱਚੋਂ',
      'todaysPractice': 'ਅੱਜ ਦਾ ਸਿਮਰਨ',
      'thisWeek': 'ਇਸ ਹਫ਼ਤੇ',
      'allTime': 'ਕੁੱਲ ਸਿਮਰਨ',
      'streak': 'ਦਿਨਾਂ ਦਾ ਲਗਾਤਾਰ ਅਭਿਆਸ',
      'practice': 'ਅਭਿਆਸ',
      'dailyGoal': 'ਰੋਜ਼ਾਨਾ ਟੀਚਾ',
      'counterStyle': 'ਕਾਊਂਟਰ ਸ਼ੈਲੀ',
      'styleMinimal': 'ਸਧਾਰਨ ਚੱਕਰ',
      'styleMala': 'ਮਣਕੇ ਦੀ ਮਾਲਾ',
      'soundAndHaptics': 'ਆਵਾਜ਼ ਅਤੇ ਕੰਬਣੀ',
      'tapSound': 'ਟੈਪ ਆਵਾਜ਼',
      'completionSound': 'ਸੰਪੂਰਨਤਾ ਆਵਾਜ਼',
      'haptics': 'ਕੰਬਣੀ (Haptics)',
      'appearance': 'ਦਿੱਖ',
      'theme': 'ਥੀਮ',
      'themeLight': 'ਲਾਈਟ',
      'themeDark': 'ਡਾਰਕ',
      'themeSystem': 'ਸਿਸਟਮ',
      'accent': 'ਰੰਗ',
      'language': 'ਭਾਸ਼ਾ',
      'data': 'ਡੇਟਾ',
      'backupData': 'ਬੈਕਅੱਪ ਐਕਸਪੋਰਟ',
      'restoreData': 'ਬੈਕਅੱਪ ਰੀਸਟੋਰ',
      'about': 'ਬਾਰੇ',
      'privacyNotice': 'ਤੁਹਾਡਾ ਸਿਮਰਨ ਤੁਹਾਡੇ ਫੋਨ ਤੇ ਹੀ ਸੁਰੱਖਿਅਤ ਹੈ।',
      'version': 'ਵਰਜਨ 1.0.0',
      'createJaap': 'ਨਵਾਂ ਜਾਪ ਜੋੜੋ',
      'editJaap': 'ਜਾਪ ਸੋਧੋ',
      'deleteJaap': 'ਜਾਪ ਹਟਾਓ',
      'deleteConfirm': 'ਕੀ ਤੁਸੀਂ ਇਸ ਜਾਪ ਨੂੰ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'save': 'ਸੰਭਾਲੋ',
      'add': 'ਜੋੜੋ',
      'delete': 'ਹਟਾਓ',
      'library': 'ਮੰਤਰ ਸੰਗ੍ਰਹਿ',
      'meditation': 'ਧਿਆਨ',
      'focusMode': 'ਇਕਾਗਰਤਾ ਮੋਡ',
      'sankalp': 'ਸੰਕਲਪ',
      'manualEntry': 'ਖੁਦ ਦਰਜ ਕਰੋ',
      'addPreviousJaap': 'ਪਿਛਲਾ ਜਾਪ ਜੋੜੋ',
      'resetCount': 'ਰੀਸੈਟ ਕਰੋ',
      'quickActions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
      'breatheSoftly': 'ਸ਼ਾਂਤ ਸਾਹ ਲਵੋ',
      'endSession': 'ਸੈਸ਼ਨ ਸਮਾਪਤ',
      'beginPractice': 'ਆਪਣੀ ਸਾਧਨਾ ਸ਼ੁਰੂ ਕਰੋ',
      'createFirstJaap': 'ਪਹਿਲਾ ਜਾਪ ਬਣਾਓ',
      'custom': 'ਕਸਟਮ',
      'noSound': 'ਬੰਦ',
      'soft': 'ਨਰਮ',
      'wood': 'ਲੱਕੜ',
      'bead': 'ਮਣਕਾ',
      'bell': 'ਘੰਟੀ',
      'templeBell': 'ਮੰਦਰ ਘੰਟੀ',
      'hapticOff': 'ਬੰਦ',
      'hapticLight': 'ਹਲਕਾ',
      'hapticMedium': 'ਮੱਧਮ',
      'dayStreak': 'ਦਿਨਾਂ ਦਾ ਸਟ੍ਰੀਕ',
      'bestStreak': 'ਸਭ ਤੋਂ ਵਧੀਆ ਸਟ੍ਰੀਕ',
      'streakCompletedToday': 'ਸਟ੍ਰੀਕ ਚਾਲੂ ਹੈ! ਤੁਸੀਂ ਅੱਜ ਮਾਲਾ ਪੂਰੀ ਕੀਤੀ ਹੈ। ਰਾਤ 12 ਵਜੇ ਤੱਕ ਤੁਹਾਡੀ ਸਟ੍ਰੀਕ ਸੁਰੱਖਿਅਤ ਹੈ।',
      'streakPendingToday': 'ਆਪਣੀ ਸਟ੍ਰੀਕ ਬਣਾਈ ਰੱਖਣ ਲਈ ਅੱਜ ਰਾਤ 12 ਵਜੇ ਤੋਂ ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ 1 ਮਾਲਾ ਜ਼ਰੂਰ ਕਰੋ!',
      'streakResetInfo': 'ਜੇਕਰ ਕੋਈ ਮਾਲਾ ਪੂਰੀ ਨਹੀਂ ਹੁੰਦੀ ਤਾਂ ਰੋਜ਼ਾਨਾ ਰਾਤ 12 ਵਜੇ ਸਟ੍ਰੀਕ ਆਪਣੇ ਆਪ ਰੀਸੈਟ ਹੋ ਜਾਂਦੀ ਹੈ।',
      'streakIncreased': 'ਸਟ੍ਰੀਕ ਵੱਧ ਗਈ!',
    },
    'gu': {
      'appName': 'જાપ',
      'tagline': 'તમારી સાધના. તમારી ગતિ.',
      'taglineSub': 'નામ સ્મરણ અને એકાગ્રતા માટે એક શાંત સ્થાન.',
      'continueBtn': 'આગળ વધો',
      'chooseLanguage': 'તમારી ભાષા પસંદ કરો',
      'whatToCount': 'તમે શેનો જાપ કરવા માંગો છો?',
      'mantraNameHint': 'મંત્ર / નામ (દા.ત. રાધે રાધે)',
      'startJaap': 'જાપ શરૂ કરો',
      'skipForNow': 'હમણાં રહેવા દો',
      'navJaap': 'જાપ',
      'navHistory': 'ઇતિહાસ',
      'navMore': 'વધુ',
      'tapToCount': 'ગણવા માટે સ્પર્શ કરો',
      'undo': 'પાછું કરો',
      'malaComplete': 'માળા પૂર્ણ',
      'mala': 'માળા',
      'malas': 'માળાઓ',
      'jaaps': 'જાપ',
      'of': 'માંથી',
      'todaysPractice': 'આજનો અભ્યાસ',
      'thisWeek': 'આ અઠવાડિયે',
      'allTime': 'કુલ સાધના',
      'streak': 'દિવસોનો અવિરત અભ્યાસ',
      'practice': 'સાધના',
      'dailyGoal': 'દૈનિક લક્ષ્ય',
      'counterStyle': 'કાઉન્ટર શૈલી',
      'styleMinimal': 'ન્યૂનતમ ચક્ર',
      'styleMala': 'મણકા માળા',
      'soundAndHaptics': 'ધ્વનિ અને કંપન',
      'tapSound': 'સ્પર્શ અવાજ',
      'completionSound': 'પૂર્ણતા અવાજ',
      'haptics': 'હેપ્ટિક પ્રતિસાદ',
      'appearance': 'દેખાવ',
      'theme': 'થીમ',
      'themeLight': 'લાઇટ',
      'themeDark': 'ડાર્ક',
      'themeSystem': 'સિસ્ટમ',
      'accent': 'રંગ',
      'language': 'ભાષા',
      'data': 'ડેટા',
      'backupData': 'બેકઅપ નિકાસ',
      'restoreData': 'બેકઅપ પુનઃસ્થાપિત',
      'about': 'વિશે',
      'privacyNotice': 'તમારી સાધના તમારા ઉપકરણ પર સુરક્ષિત છે.',
      'version': 'આવૃત્તિ 1.0.0',
      'createJaap': 'નવો જાપ ઉમેરો',
      'editJaap': 'જાપ સંપાદિત કરો',
      'deleteJaap': 'જાપ કાઢી નાખો',
      'deleteConfirm': 'શું તમે આ જાપ કાઢી નાખવા માંગો છો?',
      'cancel': 'રદ કરો',
      'save': 'સાચવો',
      'add': 'ઉમેરો',
      'delete': 'કાઢી નાખો',
      'library': 'મંત્ર સંગ્રહ',
      'meditation': 'ધ્યાન',
      'focusMode': 'એકાગ્રતા મોડ',
      'sankalp': 'સંકલ્પ',
      'manualEntry': 'મેન્યુઅલ એન્ટ્રી',
      'addPreviousJaap': 'અગાઉનો જાપ ઉમેરો',
      'resetCount': 'ગણતરી ફરી શરૂ કરો',
      'quickActions': 'ઝડપી વિકલ્પો',
      'breatheSoftly': 'શાંતિથી શ્વાસ લો',
      'endSession': 'સત્ર સમાપ્ત',
      'beginPractice': 'સાધના શરૂ કરો',
      'createFirstJaap': 'પ્રથમ જાપ બનાવો',
      'custom': 'કસ્ટમ',
      'noSound': 'બંધ',
      'soft': 'નરમ',
      'wood': 'લાકડું',
      'bead': 'મણકો',
      'bell': 'ઘંટ',
      'templeBell': 'મંદિર ઘંટ',
      'hapticOff': 'બંધ',
      'hapticLight': 'હળવું',
      'hapticMedium': 'મધ્યમ',
      'dayStreak': 'દિવસોની સ્ટ્રીક',
      'bestStreak': 'શ્રેષ્ઠ સ્ટ્રીક',
      'streakCompletedToday': 'સ્ટ્રીક સક્રિય છે! તમે આજે માળા પૂર્ણ કરી છે. રાત્રે 12:00 વાગ્યા સુધી તમારી સ્ટ્રીક સુરક્ષિત છે.',
      'streakPendingToday': 'તમારી સ્ટ્રીક જાળવી રાખવા માટે આજે રાત્રે 12:00 પહેલાં ઓછામાં ઓછી 1 માળા કરો!',
      'streakResetInfo': 'જો કોઈ માળા પૂર્ણ ન થાય તો દરરોજ રાત્રે 12:00 વાગ્યે સ્ટ્રીક આપોઆપ રીસેટ થઈ જાય છે.',
      'streakIncreased': 'સ્ટ્રીક વધી ગઈ!',
    },
    'mr': {
      'appName': 'जाप',
      'tagline': 'तुमचा सराव. तुमची गती.',
      'taglineSub': 'नामस्मरण आणि एकाग्रतेसाठी एक शांत जागा.',
      'continueBtn': 'पुढे जा',
      'chooseLanguage': 'तुमची भाषा निवडा',
      'whatToCount': 'तुम्हाला कशाचा जप करायचा आहे?',
      'mantraNameHint': 'मंत्र / नाव (उदा. राम कृष्ण हरी)',
      'startJaap': 'जप सुरू करा',
      'skipForNow': 'आता वगळा',
      'navJaap': 'जप',
      'navHistory': 'इतिहास',
      'navMore': 'अधिक',
      'tapToCount': 'मोजण्यासाठी स्पर्श करा',
      'undo': 'पूर्ववत करा',
      'malaComplete': 'माळ पूर्ण झाली',
      'mala': 'माळ',
      'malas': 'माळा',
      'jaaps': 'जप',
      'of': 'पैकी',
      'todaysPractice': 'आजचा सराव',
      'thisWeek': 'या आठवड्यात',
      'allTime': 'एकूण सराव',
      'streak': 'दिवसांचा सलग सराव',
      'practice': 'साधना',
      'dailyGoal': 'दैनंदिन उद्दिष्ट',
      'counterStyle': 'काउंटर शैली',
      'styleMinimal': 'किमान चक्र',
      'styleMala': 'मण्यांची माळ',
      'soundAndHaptics': 'ध्वनी आणि कंपन',
      'tapSound': 'स्पर्श ध्वनी',
      'completionSound': 'पूर्णता ध्वनी',
      'haptics': 'हॅप्टिक प्रतिसाद',
      'appearance': 'दिसणे',
      'theme': 'थीम',
      'themeLight': 'लाईट',
      'themeDark': 'डार्क',
      'themeSystem': 'सिस्टम',
      'accent': 'रंग',
      'language': 'भाषा',
      'data': 'डेटा',
      'backupData': 'बॅकअप निर्यात',
      'restoreData': 'बॅकअप पुनर्संचयित',
      'about': 'विषयी',
      'privacyNotice': 'तुमची साधना तुमच्या फोनवर सुरक्षित आहे.',
      'version': 'आवृत्ती 1.0.0',
      'createJaap': 'नवीन जप जोडा',
      'editJaap': 'जप संपादित करा',
      'deleteJaap': 'जप हटवा',
      'deleteConfirm': 'तुम्हाला हा जप आणि इतिहास हटवायचा आहे का?',
      'cancel': 'रद्द करा',
      'save': 'जतन करा',
      'add': 'जोडा',
      'delete': 'हटवा',
      'library': 'मंत्र संग्रह',
      'meditation': 'ध्यान',
      'focusMode': 'एकाग्रता मोड',
      'sankalp': 'संकल्प',
      'manualEntry': 'मॅन्युअल नोंद',
      'addPreviousJaap': 'मागील जप जोडा',
      'resetCount': 'गणना रीसेट करा',
      'quickActions': 'जलद क्रिया',
      'breatheSoftly': 'सहज श्वास घ्या',
      'endSession': 'सत्र समाप्त',
      'beginPractice': 'साधना सुरू करा',
      'createFirstJaap': 'पहिला जप तयार करा',
      'custom': 'सानुकूल',
      'noSound': 'बंद',
      'soft': 'हलका',
      'wood': 'काष्ठ',
      'bead': 'मणी',
      'bell': 'घंटी',
      'templeBell': 'मंदिराची घंटी',
      'hapticOff': 'बंद',
      'hapticLight': 'हलका',
      'hapticMedium': 'मध्यम',
      'dayStreak': 'दिवसांचा स्ट्रीक',
      'bestStreak': 'सर्वोत्कृष्ट स्ट्रीक',
      'streakCompletedToday': 'स्ट्रीक सक्रिय आहे! तुम्ही आज माळ पूर्ण केली आहे. मध्यरात्री १२:०० पर्यंत तुमची स्ट્રીक सुरक्षित आहे.',
      'streakPendingToday': 'तुमची स्ट્રીक टिकवून ठेवण्यासाठी आज मध्यरात्री १२:०० पूर्वी किमान १ माळ करा!',
      'streakResetInfo': 'कोणतीही माळ पूर्ण न झाल्यास दररोज मध्यरात्री १२:०० वाजता स्ट्रीक आपोआप रीसेट होते.',
      'streakIncreased': 'स्ट्रीक वाढली!',
    },
    'ta': {
      'appName': 'ஜபம்',
      'tagline': 'உங்கள் பயிற்சி. உங்கள் வேகம்.',
      'taglineSub': 'தியானம் மற்றும் எண்ணிக்கைக்கான எளிய அமைதியான இடம்.',
      'continueBtn': 'தொடரவும்',
      'chooseLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'whatToCount': 'நீங்கள் எதை ஜபிக்க விரும்புகிறீர்கள்?',
      'mantraNameHint': 'மந்திரம் / பெயர் (எ.கா. ஓம் நம சிவாய)',
      'startJaap': 'ஜபத்தைத் தொடங்கு',
      'skipForNow': 'இப்போது தவிர்',
      'navJaap': 'ஜபம்',
      'navHistory': 'வரலாறு',
      'navMore': 'மேலும்',
      'tapToCount': 'எண்ண எங்கு வேண்டுமானாலும் தொடவும்',
      'undo': 'செயல்தவிர்',
      'malaComplete': 'மாலை முடிந்தது',
      'mala': 'மாலை',
      'malas': 'மாலைகள்',
      'jaaps': 'ஜபங்கள்',
      'of': 'இல்',
      'todaysPractice': 'இன்றைய பயிற்சி',
      'thisWeek': 'இந்த வாரம்',
      'allTime': 'மொத்த பயிற்சி',
      'streak': 'நாட்கள் தொடர் பயிற்சி',
      'practice': 'பயிற்சி',
      'dailyGoal': 'தினசரி இலக்கு',
      'counterStyle': 'எண்ணிக்கை பாணி',
      'styleMinimal': 'எளிய வட்டம்',
      'styleMala': 'மணி மாலை',
      'soundAndHaptics': 'ஒலி மற்றும் அதிர்வு',
      'tapSound': 'தொடு ஒலி',
      'completionSound': 'முழுமை ஒலி',
      'haptics': 'அதிர்வு',
      'appearance': 'தோற்றம்',
      'theme': 'தீம்',
      'themeLight': 'வெளிச்சம்',
      'themeDark': 'இருள்',
      'themeSystem': 'அமைப்பு',
      'accent': 'வண்ணம்',
      'language': 'மொழி',
      'data': 'தரவு',
      'backupData': 'காப்புப்பிரதி ஏற்றுமதி',
      'restoreData': 'காப்புப்பிரதி மீட்டெடு',
      'about': 'பற்றி',
      'privacyNotice': 'உங்கள் பயிற்சி உங்கள் சாதனத்தில் பாதுகாப்பாக இருக்கும்.',
      'version': 'பதிப்பு 1.0.0',
      'createJaap': 'புதிய ஜபம் உருவாக்கு',
      'editJaap': 'ஜபம் திருத்து',
      'deleteJaap': 'ஜபம் நீக்கு',
      'deleteConfirm': 'இந்த ஜபத்தை நீக்க விரும்புகிறீர்களா?',
      'cancel': 'ரத்து',
      'save': 'சேமி',
      'add': 'சேர்',
      'delete': 'நீக்கு',
      'library': 'மந்திர நூலகம்',
      'meditation': 'தியானம்',
      'focusMode': 'கவனம் முறை',
      'sankalp': 'சங்கல்பம்',
      'manualEntry': 'கைமுறை பதிவு',
      'addPreviousJaap': 'முந்தைய ஜபம் சேர்',
      'resetCount': 'மீட்டமை',
      'quickActions': 'விரைவு செயல்கள்',
      'breatheSoftly': 'மெதுவாக சுவாசிக்கவும்',
      'endSession': 'அமர்வை முடிக்கவும்',
      'beginPractice': 'பயிற்சியைத் தொடங்குங்கள்',
      'createFirstJaap': 'முதல் ஜபத்தை உருவாக்கவும்',
      'custom': 'தனிப்பயன்',
      'noSound': 'ஆஃப்',
      'soft': 'மென்மையான',
      'wood': 'மரம்',
      'bead': 'மணி',
      'bell': 'மணி ஒலி',
      'templeBell': 'கோவில் மணி',
      'hapticOff': 'ஆஃப்',
      'hapticLight': 'மென்மை',
      'hapticMedium': 'நடுத்தரம்',
      'dayStreak': 'நாட்கள் தொடர்',
      'bestStreak': 'சிறந்த தொடர்',
      'streakCompletedToday': 'தொடர் செயலில் உள்ளது! இன்று நீங்கள் மாலையை முடித்துவிட்டீர்கள். நள்ளிரவு 12:00 வரை பாதுகாப்பானது.',
      'streakPendingToday': 'உங்கள் தொடரைத் தொடர இன்று நள்ளிரவு 12:00 மணிக்குள் குறைந்தது 1 மாலை ஜபியுங்கள்!',
      'streakResetInfo': 'எந்த மாலையும் முடிக்கப்படாவிட்டால் ஒவ்வொரு நாளும் நள்ளிரவு 12:00 மணிக்கு தொடர் தானாகவே மீட்டமைக்கப்படும்.',
      'streakIncreased': 'தொடர் அதிகரித்தது!',
    },
    'te': {
      'appName': 'జాపం',
      'tagline': 'మీ సాధన. మీ వేగం.',
      'taglineSub': 'నామస్మరణ మరియు ఏకాగ్రత కోసం ప్రశాంతమైన స్థలం.',
      'continueBtn': 'కొనసాగించు',
      'chooseLanguage': 'భాషను ఎంచుకోండి',
      'whatToCount': 'మీరు దేనిని జపించాలనుకుంటున్నారు?',
      'mantraNameHint': 'మంత్రం / నామం (ఉదా. ఓం నమః శివాయ)',
      'startJaap': 'జాపం ప్రారంభించండి',
      'skipForNow': 'ఇప్పుడు వద్దు',
      'navJaap': 'జాపం',
      'navHistory': 'చరిత్ర',
      'navMore': 'మరిన్ని',
      'tapToCount': 'లెక్కించడానికి ఎక్కడైనా తాకండి',
      'undo': 'రద్దు చేయి',
      'malaComplete': 'మాల పూర్తయింది',
      'mala': 'మాల',
      'malas': 'మాలలు',
      'jaaps': 'జాపాలు',
      'of': 'లో',
      'todaysPractice': 'నేటి సాధన',
      'thisWeek': 'ఈ వారం',
      'allTime': 'మొత్తం సాధన',
      'streak': 'రోజుల నిరంతర సాధన',
      'practice': 'సాధన',
      'dailyGoal': 'రోజువారీ లక్ష్యం',
      'counterStyle': 'కౌంటర్ శైలి',
      'styleMinimal': 'సరళమైన వృత్తం',
      'styleMala': 'పూసల మాల',
      'soundAndHaptics': 'ధ్వని & ప్రకంపనలు',
      'tapSound': 'తాకిడి శబ్దం',
      'completionSound': 'పూర్తయిన శబ్దం',
      'haptics': 'హాప్టిక్ ఫీడ్‌బ్యాక్',
      'appearance': 'రూపం',
      'theme': 'థీమ్',
      'themeLight': 'లైట్',
      'themeDark': 'డార్క్',
      'themeSystem': 'సిస్టమ్',
      'accent': 'రంగు',
      'language': 'భాష',
      'data': 'డేటా',
      'backupData': 'బ్యాకప్ ఎగుమతి',
      'restoreData': 'బ్యాకప్ పునరుద్ధరణ',
      'about': 'గురించి',
      'privacyNotice': 'మీ సాధన మీ ఫోన్‌లో సురక్షితంగా ఉంటుంది.',
      'version': 'వెర్షన్ 1.0.0',
      'createJaap': 'కొత్త జాపం జోడించండి',
      'editJaap': 'జాపం సవరించండి',
      'deleteJaap': 'జాపం తొలగించండి',
      'deleteConfirm': 'ఈ జాపంను తొలగించాలనుకుంటున్నారా?',
      'cancel': 'రద్దు',
      'save': 'సేవ్',
      'add': 'జోడించు',
      'delete': 'తొలగించు',
      'library': 'మంత్ర భాండాగారం',
      'meditation': 'ధ్యానం',
      'focusMode': 'ఏకాగ్రత మోడ్',
      'sankalp': 'సంకల్పం',
      'manualEntry': 'మాన్యువల్ ఎంట్రీ',
      'addPreviousJaap': 'మునుపటి జాపం జోడించండి',
      'resetCount': 'రీసెట్ చేయండి',
      'quickActions': 'త్వరిత చర్యలు',
      'breatheSoftly': 'నెమ్మదిగా శ్వాస తీసుకోండి',
      'endSession': 'ముగించు',
      'beginPractice': 'సాధన ప్రారంభించండి',
      'createFirstJaap': 'మొదటి జాపం సృష్టించండి',
      'custom': 'కస్టమ్',
      'noSound': 'ఆఫ్',
      'soft': 'మృదువైన',
      'wood': 'చెక్క',
      'bead': 'పూస',
      'bell': 'గంట',
      'templeBell': 'గుడి గంట',
      'hapticOff': 'ఆఫ్',
      'hapticLight': 'తేలికైన',
      'hapticMedium': 'మధ్యస్థం',
      'dayStreak': 'రోజుల స్ట్రీక్',
      'bestStreak': 'ఉత్తమ స్ట్రీక్',
      'streakCompletedToday': 'స్ట్రీక్ సక్రియంగా ఉంది! మీరు ఈరోజు మాల పూర్తి చేశారు. అర్ధరాత్రి 12:00 వరకు సురక్షితం.',
      'streakPendingToday': 'మీ స్ట్రీక్‌ను కొనసాగించడానికి ఈరోజు అర్ధరాత్రి 12:00 లోపు కనీసం 1 మాల జపించండి!',
      'streakResetInfo': 'ఎటువంటి మాల పూర్తి కాకపోతే ప్రతిరోజూ అర్ధరాత్రి 12:00 గంటలకు స్ట్రీక్ స్వయంచాలకంగా రీసెట్ అవుతుంది.',
      'streakIncreased': 'స్ట్రీక్ పెరిగింది!',
    },
    'kn': {
      'appName': 'ಜಪ',
      'tagline': 'ನಿಮ್ಮ ಅಭ್ಯಾಸ. ನಿಮ್ಮ ವೇಗ.',
      'taglineSub': 'ಧ್ಯಾನ ಮತ್ತು ಎಣಿಕೆಗೆ ಶಾಂತಿಯುತ ಸ್ಥಳ.',
      'continueBtn': 'ಮುಂದುವರಿಯಿರಿ',
      'chooseLanguage': 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'whatToCount': 'ನೀವು ಏನನ್ನು ಜಪಿಸಲು ಬಯಸುತ್ತೀರಿ?',
      'mantraNameHint': 'ಮಂತ್ರ / ಹೆಸರು (ಉದಾ. ಓಂ ನಮಃ ಶಿವಾಯ)',
      'startJaap': 'ಜಪ ಪ್ರಾರಂಭಿಸಿ',
      'skipForNow': 'ಈಗ ಬೇಡ',
      'navJaap': 'ಜಪ',
      'navHistory': 'ಇತಿಹಾಸ',
      'navMore': 'ಇನ್ನಷ್ಟು',
      'tapToCount': 'ಎಣಿಸಲು ಎಲ್ಲಿಯಾದರೂ ಸ್ಪರ್ಶಿಸಿ',
      'undo': 'ರದ್ದುಮಾಡಿ',
      'malaComplete': 'ಮಾಲೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'mala': 'ಮಾಲೆ',
      'malas': 'ಮಾಲೆಗಳು',
      'jaaps': 'ಜಪಗಳು',
      'of': 'ರಲ್ಲಿ',
      'todaysPractice': 'ಇಂದಿನ ಅಭ್ಯಾಸ',
      'thisWeek': 'ಈ ವಾರ',
      'allTime': 'ಒಟ್ಟು ಅಭ್ಯಾಸ',
      'streak': 'ದಿನಗಳ ನಿರಂತರ ಅಭ್ಯಾಸ',
      'practice': 'ಅಭ್ಯಾಸ',
      'dailyGoal': 'ದೈನಂದಿನ ಗುರಿ',
      'counterStyle': 'ಕೌಂಟರ್ ಶೈಲಿ',
      'styleMinimal': 'ಸರಳ ವೃತ್ತ',
      'styleMala': 'ಮಣಿಗಳ ಮಾಲೆ',
      'soundAndHaptics': 'ಧ್ವನಿ ಮತ್ತು ಕಂಪನ',
      'tapSound': 'ಸ್ಪರ್ಶ ಧ್ವನಿ',
      'completionSound': 'ಪೂರ್ಣಗೊಂಡ ಧ್ವನಿ',
      'haptics': 'ಹ್ಯಾಪ್ಟಿಕ್ ಕಂಪನ',
      'appearance': 'ಗೋಚರತೆ',
      'theme': 'ಥೀಮ್',
      'themeLight': 'ಬೆಳಕು',
      'themeDark': 'ಕತ್ತಲೆ',
      'themeSystem': 'ವ್ಯವಸ್ಥೆ',
      'accent': 'ಬಣ್ಣ',
      'language': 'ಭಾಷೆ',
      'data': 'ಡೇಟಾ',
      'backupData': 'ಬ್ಯಾಕಪ್ ರಫ್ತು',
      'restoreData': 'ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪನೆ',
      'about': 'ಬಗ್ಗೆ',
      'privacyNotice': 'ನಿಮ್ಮ ಅಭ್ಯಾಸ ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದೆ.',
      'version': 'ಆವೃತ್ತಿ 1.0.0',
      'createJaap': 'ಹೊಸ ಜಪ ರಚಿಸಿ',
      'editJaap': 'ಜಪ ಸಂಪಾದಿಸಿ',
      'deleteJaap': 'ಜಪ ಅಳಿಸಿ',
      'deleteConfirm': 'ಈ ಜಪವನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?',
      'cancel': 'ರದ್ದು',
      'save': 'ಉಳಿಸಿ',
      'add': 'ಸೇರಿಸಿ',
      'delete': 'ಅಳಿಸಿ',
      'library': 'ಮಂತ್ರ ಗ್ರಂಥಾಲಯ',
      'meditation': 'ಧ್ಯಾನ',
      'focusMode': 'ಏಕಾಗ್ರತೆ ಮೋಡ್',
      'sankalp': 'ಸಂಕಲ್ಪ',
      'manualEntry': 'ಹಸ್ತಚಾಲಿತ ನಮೂದು',
      'addPreviousJaap': 'ಹಿಂದಿನ ಜಪ ಸೇರಿಸಿ',
      'resetCount': 'ಮರುಹೊಂದಿಸಿ',
      'quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
      'breatheSoftly': 'ನಿಧಾನವಾಗಿ ಉಸಿರಾಡಿ',
      'endSession': 'ಅಧಿವೇಶನ ಮುಕ್ತಾಯ',
      'beginPractice': 'ಅಭ್ಯಾಸವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
      'createFirstJaap': 'ಮೊದಲ ಜಪ ರಚಿಸಿ',
      'custom': 'ಕಸ್ಟಮ್',
      'noSound': 'ಆಫ್',
      'soft': 'ಮೃದು',
      'wood': 'ಮರ',
      'bead': 'ಮಣಿ',
      'bell': 'ಗಂಟೆ',
      'templeBell': 'ದೇವಾಲಯದ ಗಂಟೆ',
      'hapticOff': 'ಆಫ್',
      'hapticLight': 'ಲಘು',
      'hapticMedium': 'ಮಧ್ಯಮ',
      'dayStreak': 'ದಿನಗಳ ಸ್ಟ್ರೀಕ್',
      'bestStreak': 'ಅತ್ಯುತ್ತಮ ಸ್ಟ್ರೀಕ್',
      'streakCompletedToday': 'ಸ್ಟ್ರೀಕ್ ಸಕ್ರಿಯವಾಗಿದೆ! ನೀವು ಇಂದು ಮಾಲೆ ಪೂರ್ಣಗೊಳಿಸಿದ್ದೀರಿ. ಮಧ್ಯರಾತ್ರಿ 12:00 ರವರೆಗೆ ಸುರಕ್ಷಿತ.',
      'streakPendingToday': 'ನಿಮ್ಮ ಸ್ಟ್ರೀಕ್ ಉಳಿಸಿಕೊಳ್ಳಲು ಇಂದು ಮಧ್ಯರಾತ್ರಿ 12:00 ರ ಮೊದಲು ಕನಿಷ್ಠ 1 ಮಾಲೆ ಜಪಿಸಿ!',
      'streakResetInfo': 'ಯಾವುದೇ ಮಾಲೆ ಪೂರ್ಣಗೊಳ್ಳದಿದ್ದರೆ ಪ್ರತಿದಿನ ಮಧ್ಯರಾತ್ರಿ 12:00 ಕ್ಕೆ ಸ್ಟ್ರೀಕ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಮರುಹೊಂದಿಸಲ್ಪಡುತ್ತದೆ.',
      'streakIncreased': 'ಸ್ಟ್ರೀಕ್ ಹೆಚ್ಚಾಗಿದೆ!',
    },
    'ml': {
      'appName': 'ജപം',
      'tagline': 'നിങ്ങളുടെ സാധന. നിങ്ങളുടെ വേഗത.',
      'taglineSub': 'നാമജപത്തിനും ധ്യാനത്തിനുമുള്ള ശാന്തമായ ഇടം.',
      'continueBtn': 'തുടരുക',
      'chooseLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'whatToCount': 'നിങ്ങൾ എന്ത് ജപിക്കാൻ ആഗ്രഹിക്കുന്നു?',
      'mantraNameHint': 'മന്ത്രം / നാമം (ഉദാ. രാധേ രാധേ)',
      'startJaap': 'ജപം ആരംഭിക്കുക',
      'skipForNow': 'ഇപ്പോൾ ഒഴിവാക്കുക',
      'navJaap': 'ജപം',
      'navHistory': 'ചരിത്രം',
      'navMore': 'കൂടുതൽ',
      'tapToCount': 'എണ്ണാൻ സ്പർശിക്കുക',
      'undo': 'പൂർവ്വസ്ഥിതിയിലാക്കുക',
      'malaComplete': 'മാല പൂർത്തിയായി',
      'mala': 'മാല',
      'malas': 'മാലകൾ',
      'jaaps': 'ജപങ്ങൾ',
      'of': '-ൽ',
      'todaysPractice': 'ഇന്നത്തെ സാധന',
      'thisWeek': 'ഈ ആഴ്ച',
      'allTime': 'ആകെ സാധന',
      'streak': 'ദിവസത്തെ തുടർച്ചയായ സാധന',
      'practice': 'സാധന',
      'dailyGoal': 'ദൈനംദിന ലക്ഷ്യം',
      'counterStyle': 'കൗണ്ടർ ശൈലി',
      'styleMinimal': 'ലളിതമായ വൃത്തം',
      'styleMala': 'മണി മാല',
      'soundAndHaptics': 'ശബ്ദവും വിറയലും',
      'tapSound': 'സ്പർശന ശബ്ദം',
      'completionSound': 'പൂർത്തീകരണ ശബ്ദം',
      'haptics': 'ഹാപ്റ്റിക്സ്',
      'appearance': 'കാഴ്ച',
      'theme': 'തീം',
      'themeLight': 'ലൈറ്റ്',
      'themeDark': 'ഡാർക്ക്',
      'themeSystem': 'സിസ്റ്റം',
      'accent': 'നിറം',
      'language': 'ഭാഷ',
      'data': 'ഡാറ്റ',
      'backupData': 'ബാക്കപ്പ് എക്സ്പോർട്ട്',
      'restoreData': 'ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക',
      'about': 'കുറിച്ച്',
      'privacyNotice': 'നിങ്ങളുടെ സാധന നിങ്ങളുടെ ഫോണിൽ സുരക്ഷിതമാണ്.',
      'version': 'പതിപ്പ് 1.0.0',
      'createJaap': 'പുതിയ ജപം ചേർക്കുക',
      'editJaap': 'ജപം മാറ്റുക',
      'deleteJaap': 'ജപം ഇല്ലാതാക്കുക',
      'deleteConfirm': 'ഈ ജപം ഇല്ലാതാക്കണോ?',
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സംരക്ഷിക്കുക',
      'add': 'ചേർക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'library': 'മന്ത്ര ശേഖരം',
      'meditation': 'ധ്യാനം',
      'focusMode': 'ഫോക്കസ് മോഡ്',
      'sankalp': 'സങ്കൽപ്പം',
      'manualEntry': 'മാനുവൽ എൻട്രി',
      'addPreviousJaap': 'മുമ്പത്തെ ജപം ചേർക്കുക',
      'resetCount': 'റീസെറ്റ് ചെയ്യുക',
      'quickActions': 'പെട്ടെന്നുള്ള പ്രവർത്തനങ്ങൾ',
      'breatheSoftly': 'പതുക്കെ ശ്വാസമെടുക്കുക',
      'endSession': 'അവസാനിപ്പിക്കുക',
      'beginPractice': 'സാധന ആരംഭിക്കുക',
      'createFirstJaap': 'ആദ്യത്തെ ജപം ഉണ്ടാക്കുക',
      'custom': 'കസ്റ്റം',
      'noSound': 'ഓഫ്',
      'soft': 'മൃദുവായ',
      'wood': 'മരം',
      'bead': 'മണി',
      'bell': 'മണിനാദം',
      'templeBell': 'ക്ഷേത്ര മണി',
      'hapticOff': 'ഓഫ്',
      'hapticLight': 'നേർത്ത',
      'hapticMedium': 'ഇടത്തരം',
      'dayStreak': 'ദിവസത്തെ സ്ട്രീക്ക്',
      'bestStreak': 'ഏറ്റവും മികച്ച സ്ട്രീക്ക്',
      'streakCompletedToday': 'സ്ട്രീക്ക് സജീവമാണ്! നിങ്ങൾ ഇന്ന് മാല പൂർത്തിയാക്കി. അർദ്ധരാത്രി 12:00 വരെ സുരക്ഷിതമാണ്.',
      'streakPendingToday': 'സ്ട്രീക്ക് നിലനിർത്താൻ ഇന്ന് അർദ്ധരാത്രി 12:00-ന് മുമ്പ് കുറഞ്ഞത് 1 മാലയെങ്കിലും ജപിക്കുക!',
      'streakResetInfo': 'മാലയൊന്നും പൂർത്തിയായില്ലെങ്കിൽ എല്ലാ ദിവസവും അർദ്ധരാത്രി 12:00-ന് സ്ട്രീക്ക് സ്വയമേവ റീസെറ്റ് ആകുന്നു.',
      'streakIncreased': 'സ്ട്രീക്ക് വർദ്ധിച്ചു!',
    },
    'or': {
      'appName': 'ଜପ',
      'tagline': 'ଆପଣଙ୍କ ସାଧନା। ଆପଣଙ୍କ ଗତି।',
      'taglineSub': 'ନାମ ଜପ ଏବଂ ଏକାଗ୍ରତା ପାଇଁ ଏକ ଶାନ୍ତ ସ୍ଥାନ।',
      'continueBtn': 'ଆଗକୁ ବଢ଼ନ୍ତୁ',
      'chooseLanguage': 'ଭାଷା ବାଛନ୍ତୁ',
      'whatToCount': 'ଆପଣ କେଉଁ ନାମ ଜପ କରିବାକୁ ଚାହାଁନ୍ତି?',
      'mantraNameHint': 'ମନ୍ତ୍ର / ନାମ (ଯଥା: ରାଧେ ରାଧେ)',
      'startJaap': 'ଜପ ଆରମ୍ଭ କରନ୍ତୁ',
      'skipForNow': 'ବର୍ତ୍ତମାନ ଛାଡନ୍ତୁ',
      'navJaap': 'ଜପ',
      'navHistory': 'ଇତିହାସ',
      'navMore': 'ଅଧିକ',
      'tapToCount': 'ଗଣିବା ପାଇଁ ସ୍ପର୍ଶ କରନ୍ତୁ',
      'undo': 'ପୂର୍ବବତ୍',
      'malaComplete': 'ମାଳା ସମ୍ପୂର୍ଣ୍ଣ',
      'mala': 'ମାଳା',
      'malas': 'ମାଳାଗୁଡିକ',
      'jaaps': 'ଜପ',
      'of': 'ରୁ',
      'todaysPractice': 'ଆଜିର ସାଧନା',
      'thisWeek': 'ଏହି ସପ୍ତାହ',
      'allTime': 'ସମୁଦାୟ ସାଧନା',
      'streak': 'ଦିନର ନିରନ୍ତର ସାଧନା',
      'practice': 'ସାଧନା',
      'dailyGoal': 'ଦୈନିକ ଲକ୍ଷ୍ୟ',
      'counterStyle': 'କାଉଣ୍ଟର ଶୈଳୀ',
      'styleMinimal': 'ସରଳ ବୃତ୍ତ',
      'styleMala': 'ମାଳି ମାଳା',
      'soundAndHaptics': 'ଶବ୍ଦ ଏବଂ କମ୍ପନ',
      'tapSound': 'ସ୍ପର୍ଶ ଶବ୍ଦ',
      'completionSound': 'ସମାପ୍ତି ଶବ୍ଦ',
      'haptics': 'ହାପ୍ଟିକ କମ୍ପନ',
      'appearance': 'ଦୃଶ୍ୟ',
      'theme': 'ଥିମ୍',
      'themeLight': 'ଲାଇଟ୍',
      'themeDark': 'ଡାର୍କ',
      'themeSystem': 'ସିଷ୍ଟମ',
      'accent': 'ରଙ୍ଗ',
      'language': 'ଭାଷା',
      'data': 'ଡାଟା',
      'backupData': 'ବ୍ୟାକଅପ୍ ରପ୍ତାନି',
      'restoreData': 'ବ୍ୟାକଅପ୍ ପୁନରୁଦ୍ଧାର',
      'about': 'ବିଷୟରେ',
      'privacyNotice': 'ଆପଣଙ୍କ ସାଧନା ଆପଣଙ୍କ ଫୋନରେ ସୁରକ୍ଷିତ।',
      'version': 'ସଂସ୍କରଣ 1.0.0',
      'createJaap': 'ନୂଆ ଜପ ଯୋଡନ୍ତୁ',
      'editJaap': 'ଜପ ସଂଶୋଧନ',
      'deleteJaap': 'ଜପ ହଟାନ୍ତୁ',
      'deleteConfirm': 'ଏହି ଜପ ହଟାଇବାକୁ ଚାହାଁନ୍ତି କି?',
      'cancel': 'ବାତିଲ',
      'save': 'ସାଇତନ୍ତୁ',
      'add': 'ଯୋଡନ୍ତୁ',
      'delete': 'ହଟାନ୍ତୁ',
      'library': 'ମନ୍ତ୍ର ସଂଗ୍ରହ',
      'meditation': 'ଧ୍ୟାନ',
      'focusMode': 'ଏକାଗ୍ରତା ମୋଡ୍',
      'sankalp': 'ସଂକଳ୍ପ',
      'manualEntry': 'ମାନୁଆଲ୍ ଏଣ୍ଟ୍ରି',
      'addPreviousJaap': 'ପୂର୍ବ ଜପ ଯୋଡନ୍ତୁ',
      'resetCount': 'ରିସେଟ୍ କରନ୍ତୁ',
      'quickActions': 'ଶୀଘ୍ର କାର୍ଯ୍ୟ',
      'breatheSoftly': 'ଧୀରେ ନିଶ୍ୱାସ ନିଅନ୍ତୁ',
      'endSession': 'ସମାପ୍ତ',
      'beginPractice': 'ସାଧନା ଆରମ୍ଭ କରନ୍ତୁ',
      'createFirstJaap': 'ପ୍ରଥମ ଜପ ସୃଷ୍ଟି କରନ୍ତୁ',
      'custom': 'କଷ୍ଟମ୍',
      'noSound': 'ବନ୍ଦ',
      'soft': 'କୋମଳ',
      'wood': 'କାଠ',
      'bead': 'ମାଳି',
      'bell': 'ଘଣ୍ଟି',
      'templeBell': 'ମନ୍ଦିର ଘଣ୍ଟି',
      'hapticOff': 'ବନ୍ଦ',
      'hapticLight': 'ହାଲୁକା',
      'hapticMedium': 'ମଧ୍ୟମ',
      'dayStreak': 'ଦିନର ଷ୍ଟ୍ରିକ',
      'bestStreak': 'ସର୍ବୋତ୍ତମ ଷ୍ଟ୍ରିକ',
      'streakCompletedToday': 'ଷ୍ଟ୍ରିକ ସକ୍ରିୟ ଅଛି! ଆପଣ ଆଜି ମାଳା ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି। ରାତି ୧୨:୦୦ ପର୍ଯ୍ୟନ୍ତ ସୁରକ୍ଷିତ।',
      'streakPendingToday': 'ଆପଣଙ୍କ ଷ୍ଟ୍ରିକ ବଜାୟ ରଖିବାକୁ ଆଜି ରାତି ୧୨:୦୦ ପୂର୍ବରୁ ଅତି କମରେ ୧ ମାଳା ଜପ କରନ୍ତୁ!',
      'streakResetInfo': 'ଯଦି କୌଣସି ମାଳା ସମ୍ପୂର୍ଣ୍ଣ ନହୁଏ, ତେବେ ପ୍ରତିଦିନ ରାତି ୧୨:୦୦ ରେ ଷ୍ଟ୍ରିକ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ରିସେଟ୍ ହୋଇଯାଏ।',
      'streakIncreased': 'ଷ୍ଟ୍ରିକ ବୃଦ୍ଧି ପାଇଲା!',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class LanguageItem {
  final String code;
  final String name;
  final String nativeName;

  const LanguageItem({
    required this.code,
    required this.name,
    required this.nativeName,
  });
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'bn', 'pa', 'gu', 'mr', 'ta', 'te', 'kn', 'ml', 'or']
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
